### ISSUE TITLE
Runtime dependencies should be included in the .tomcatplugin classpath

### ISSUE THREAD

**Issue by balapal** [anjlab/gradle-sysdeo-tomcat-plugin#2]
Hi,

I have just noticed that my runtime dependencies are not included in the classpath in .tomcatplugin file.
I think this plugin should generate the dependency based on runtime dependencies (which include compile dependencies).

> **runtime**
>    The dependencies required by the production classes at runtime. By default, also includes the compile time dependencies.

Source: 8.3 Dependency Configuration http://gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html

**Comment by dmitrygusev** [comment]
@balapal thanks for mentioning, please try version 1.0.5

**Comment by balapal** [comment]
Looks good, thanks
