### ISSUE TITLE
Version 1.0.6 requires Java 1.8

### ISSUE THREAD

**Issue by lorenet** [anjlab/gradle-sysdeo-tomcat-plugin#5]
Version 1.0.6 is built by Java 1.8:
`> java.lang.UnsupportedClassVersionError: com/anjlab/gradle/SysdeoEclipseTomcatGeneratorPlugin : Unsupported major.minor version 52.0`

Is it really necessary?
I need to stay on 1.6.

Thanks!

**Comment by dmitrygusev** [comment]
@lorenet 1.8 not necessary here, I've fixed the target to 1.6, please try version 1.0.7

**Comment by lorenet** [comment]
@dmitrygusev It's fine, thankyou!
